<a href="https://colab.research.google.com/github/carlosramos1/practicas-machine-learning/blob/main/Regresion_Logistica_Multinominal_(mi_impl).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
# Importar librerias
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing

## Gradiente Descendente

In [65]:
XX = np.ones((5,4))
KK = 3
theta = np.random.uniform(low=0, high=1, size=(XX.shape[1],KK))
theta

array([[0.36566077, 0.57766599, 0.30136033],
       [0.76900757, 0.2976799 , 0.99740597],
       [0.95920877, 0.30781027, 0.50600635],
       [0.65250806, 0.82520135, 0.06701301]])

In [66]:
def gradient_descent(X, Y, alpha=0.01, epochs=1000):
    K = Y.shape[1]
    np.random.seed(1432)
    theta = np.random.uniform(low=0, high=1, size=(X.shape[1],K))
    for i in range(epochs):
        theta = theta - alpha*gradient_J(theta, X, Y)
    return theta

In [67]:
# Gradiente de la función de costo  d_J/d_theta
def gradient_J(theta, X, y):
  PI = softmax(X, theta)
  return - X.T @ (y - PI)

In [68]:
def softmax(X, theta):
  n = X.shape[0]
  Z = X @ theta
  num = np.exp(Z)
  den = []
  for i in range(n):
    den.append(np.sum(np.exp(Z[i,:])))
  den = np.array(den).reshape((n,1))
  return num/den

In [69]:
zi1 = 2
zi2 = 1
zi3 = 0
K = 2
Z = np.array([[zi1,zi2,zi3],
              [0.1,0.3,0.4]])
num = np.exp(Z)
den = []
for i in range(2):
  den.append(np.sum(np.exp(Z[i,:])))

den = np.array(den).reshape((K,1))
num/den

array([[0.66524096, 0.24472847, 0.09003057],
       [0.28001309, 0.34200877, 0.37797814]])

## Preparación de datos

### Datos de prueba

In [70]:
# Lectura de datos
url = 'https://raw.githubusercontent.com/carlosramos1/datosML/refs/heads/main/newthyroid.csv'
thyroids = pd.read_csv(url)

# Renombrar columnas
thyroids.columns = ['T3','TRX','TRI','TRS','TSH','Tipo']
thyroids.head()

T3   TRX  TRI  TRS  TSH  Tipo
0  107  10.1  2.2  0.9  2.7     1
1  113   9.9  3.1  2.0  5.9     1
2  127  12.9  2.4  1.4  0.6     1
3  109   5.3  1.6  1.4  1.5     1
4  105   7.3  1.5  1.5 -0.1     1

In [71]:
# Establecer la variable predictoria X ademas añadir 1s en la 1ra columna

# Número de observaciones
n = thyroids.shape[0]

# Definir matriz de datos
X_data = thyroids.loc[:,['T3','TRX','TRI','TRS','TSH']]

# normalizacion z-score
X_z = preprocessing.scale(X_data)

x0 = np.ones(n)
X = np.column_stack((x0,X_z))

X[:5]

array([[ 1.        , -0.19789404,  0.0630222 ,  0.10575442, -0.32438883,
        -0.18617988],
       [ 1.        ,  0.25960294,  0.02034575,  0.74126623, -0.14417281,
         0.21125033],
       [ 1.        ,  1.32709588,  0.6604925 ,  0.24697927, -0.24247246,
        -0.44699346],
       [ 1.        , -0.04539505, -0.9612126 , -0.31792012, -0.24247246,
        -0.33521621],
       [ 1.        , -0.35039303, -0.5344481 , -0.38853255, -0.22608918,
        -0.53393132]])

In [72]:
# Establecer la var. de respuestas 'y'
y = np.array(thyroids.loc[:,['Tipo']])
K = np.unique(y).size

# Transformar 'y' a una matriz Y binarización (codificación one-hot)
binarizer = preprocessing.LabelBinarizer()
binarizer.fit([k+1 for k in range(K)])

Y = binarizer.transform(y)
Y[:5]

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]])

## Entrenamiento

### Cálculo de los parámetros $\theta$

In [73]:
# Calcular los parametros theta, mediante el método
# Gradiente Decendente
thetas = gradient_descent(X, Y)
thetas

array([[ 6.79405579, -1.75493617, -2.41558745],
       [ 1.86063566, -1.94030812,  1.65829243],
       [ 0.56761752,  7.82059385, -8.00850548],
       [-0.85012253,  4.38833499, -2.17814431],
       [-0.19316034, -0.77079177,  2.66029849],
       [-0.02789271, -2.75705709,  4.77661669]])

## Predicciones

In [74]:
# Probabilidades estimadas
Probs = softmax(X, thetas)
Probs.round(3)
Probs[:5]

array([[9.97731720e-01, 2.25975822e-03, 8.52135634e-06],
       [9.97469031e-01, 2.47661760e-03, 5.43509406e-05],
       [9.97868719e-01, 2.13127020e-03, 1.11454568e-08],
       [9.44653674e-01, 1.10801191e-07, 5.53462152e-02],
       [9.99280398e-01, 9.71581358e-06, 7.09886608e-04]])

In [75]:
# Estimaciones de la varaible de respeusta
y_hat = np.argmax(Probs, axis=1)+1
y_hat

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3])

In [76]:
# veamos la variable original
y.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [77]:
# Matriz de confusión
cm = confusion_matrix(y, y_hat)
print(cm)

[[149   1   0]
 [  0  35   0]
 [  1   0  29]]


In [78]:
# Medida de aciertos
((np.diag(cm).sum())/y.size)*100

np.float64(99.06976744186046)

In [79]:
# Medida de error
(1-(np.diag(cm).sum())/y.size)*100

np.float64(0.9302325581395321)