<a href="https://colab.research.google.com/github/carlosramos1/practicas-machine-learning/blob/main/Regresion_Logistica_(mi_impl).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importar librerias
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix

## Gradiente Descendente

In [ ]:
def gradient_descent(X, y, alpha=0.01, epocs=1000):
    np.random.seed(1432)
    theta = np.random.uniform(low=0, high=1, size=(X.shape[1],1))
    for i in range(epocs):
        theta = theta - alpha*grad_costo(theta, X, y)
    return theta

In [ ]:
# Gradiente de la función de costo  d_J/d_theta
def grad_costo(theta, X, y):
  sig_z = sigmoide(X @ theta)
  return - X.T @ (y - sig_z)

In [ ]:
def sigmoide(z):
  return 1/(1+np.exp(-z))

## Datos de prueba

En el siguiente conjunto de datos de postulantes a un puesto de trabajo, tenemos:

__Variable de respuesta__

* $Aceptado_i$: Indicatriz de que el postulante $i$ es aceptado.

__Variables predictoras__

* $Atrasado_i$: Indicatriz de que el postulante $i$ llegó tarde a la entrevista de trabajo.
* $PromPruebas_i$: Promedio de todas las pruebas que tomó el candidato $i$.

In [ ]:
# Lectura de datos
data = pd.DataFrame(np.matrix([[1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0],
                               [1,1,1,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0],
                               [70,80,50,60,40,65,75,80,70,60,65,50,45,35,40,50,55,45,50,60]]).T,
                    columns=['Aceptado','Atrasado','PromPruebas'])
data.head()

Aceptado  Atrasado  PromPruebas
0         1         1           70
1         1         1           80
2         1         1           50
3         1         0           60
4         1         0           40

In [ ]:
# Establecer la variable predictoria X ademas añadir 1s en la 1ra columna
X = data[['Atrasado','PromPruebas']].values
ones = np.ones((X.shape[0], 1))
X = np.concatenate([ones, X], axis=1)
X[:5]

array([[ 1.,  1., 70.],
       [ 1.,  1., 80.],
       [ 1.,  1., 50.],
       [ 1.,  0., 60.],
       [ 1.,  0., 40.]])

In [ ]:
# Establecer la var. de respuestas 'y' como un vector columna
y = data['Aceptado'].values
y = y.reshape((y.size, 1))
y.shape

(20, 1)

In [ ]:
# Calcular los parametros theta, mediante el método
# Gradiente Decendente
thetas = gradient_descent(X, y)
thetas

array([[-12.18547685],
       [-18.91576428],
       [  0.6801378 ]])

Haciendo nuevamente el cálculo pero esta vez normalizando los datos

In [ ]:
# normalización z score de datos
def normalizacion_z(x):
  return (x - np.mean(x)) / np.std(x)

In [ ]:
# Normalizando los datos, en este caso solo es necesario la columna 3
# porque las demas cols ya tienen valores entre 0 y 1
X[:,2] = normalizacion_z(X[:,2])
X[:5]

array([[ 1.        ,  1.        ,  0.97448276],
       [ 1.        ,  1.        ,  1.73878296],
       [ 1.        ,  1.        , -0.55411765],
       [ 1.        ,  0.        ,  0.21018256],
       [ 1.        ,  0.        , -1.31841785]])

In [ ]:
# Obtengamos los parametros theta
thetas = gradient_descent(X, y)
thetas

array([[ 0.45053071],
       [-1.02143633],
       [ 1.55751556]])

In [ ]:
# Predecir para los mismos datos
y_hat = np.round(sigmoide(X @ thetas))
y_hat.flatten().astype(int)

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [ ]:
# verificando con el original
y.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Matriz de confusión
cm_gd = confusion_matrix(y, np.round(sigmoide(X @ thetas), 0))
print(cm_gd)

[[7 3]
 [2 8]]


In [ ]:
# Medida de aciertos
(cm_gd[0,0]+cm_gd[1,1])/y.size

np.float64(0.75)