<a href="https://colab.research.google.com/github/carlosramos1/practicas-machine-learning/blob/main/Regresion_Lineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import linalg as LA
plt.style.use('ggplot')

Construimos datos de prueba

In [ ]:
# Tamaño de muestra
n=100

# Regresores
np.random.seed(8888)
x1 = np.random.uniform(low=0, high=15, size=(n,))
np.random.seed(4258)
x2 = np.random.uniform(low=20, high=80, size=(n,))
np.random.seed(3456)
x3 = np.random.uniform(low=10, high=40, size=(n,))

# Error
np.random.seed(4321)
E = np.random.normal(loc=0.0, scale=10, size=n)

# Variable respuesta
Y=20.5+3.8*x1+6.5*x2+10*x3+E

## Método de mínimos cuadrados

Minimizar RSS para encontrar los parámetros $\beta$ 's

In [ ]:
# 1. Escribir X como una matriz de tamaño N x (p+1),
#    es decir, N filas y (p+1) columanas
#    donde la primera columna es de 1s'.
ones = np.ones(n)
X = np.array((ones,x1,x2,x3)).T
X.shape

(100, 4)

In [ ]:
# 2. escribir 'y' como un vector columna
y = Y.reshape((100,1))
y.shape

(100, 1)

In [ ]:
# 3. Estimar los parámetros Beta's
Xt_X = X.T @ X
Xt_y = X.T @ y

beta_hat = LA.inv(Xt_X) @ Xt_y
beta_hat

array([[26.79295998],
       [ 3.2388939 ],
       [ 6.57385373],
       [ 9.73114711]])

In [ ]:
# Si comparamos con Y=20.5+3.8*x1+6.5*x2+10*x3+E, tiene cierta similitud.

## Gradiente descendiente

In [ ]:
# Primero estandaricemos nuestras variables....
z0 = np.copy(ones)
z1 = (x1 - np.mean(x1))/np.std(x1)
z2 = (x2 - np.mean(x2))/np.std(x2)
z3 = (x3 - np.mean(x3))/np.std(x3)

In [ ]:
Z = np.array((z0,z1,z2,z3)).T
Z.shape

(100, 4)

In [ ]:
y.shape

(100, 1)

In [ ]:
# Definamos la función del gradiente del costo...
def grad_costo(beta, X, Y):
    grad_costo = X.T @ ((X@beta) - Y)
    return(grad_costo)

In [ ]:
# Definamos el algoritmo de gradient descent...
def gradient_descent(X, Y, alpha=0.01, epocs=1000):
    np.random.seed(1432)
    beta = np.random.uniform(low=0, high=1, size=(X.shape[1],1))
    for i in range(epocs):
        beta = beta-alpha*grad_costo(beta, X, Y)
    return beta

In [ ]:
# Obtengamos los estimadores...
beta = gradient_descent(Z, y, alpha=0.001, epocs=100)
print(beta)

[[645.77438576]
 [ 14.21359118]
 [113.64555245]
 [ 90.04283691]]


In [ ]:
# Finalmente, obtengamos los estimadores no estandarizados...
B_gd=np.zeros((4,1))
B_gd[1,]=beta[1,]/np.std(x1)
B_gd[2,]=beta[2,]/np.std(x2)
B_gd[3,]=beta[3,]/np.std(x3)
B_gd[0,]=beta[0,]-(B_gd[1,]*np.mean(x1)
                   +B_gd[2,]*np.mean(x2)
                   +B_gd[3,]*np.mean(x3))
print(B_gd)

[[26.84728739]
 [ 3.23522308]
 [ 6.5738314 ]
 [ 9.72941852]]
